# Generated by Django 4.2.11 on 2024-04-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_management', '0002_rename_reply_complaints_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='reply',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
